{
 "title": "Flink Metrics",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Task Manager",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_initializationTime,host)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({host=~\"$host\"},job_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Jobmanager Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registered TMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "flink_jobmanager_job_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Job Throughput Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Records Out/sec",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~\"Source:.*\", host=\"$host\", job_name=~\"$job\"}",
     "legendFormat": "{{job_name}} {{task_name}}"
    }
   ]
  },
  {
   "title": "NumBytesIn",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesIn{task_name=~\".*Writer*\", host=~\"$host\"}",
     "legendFormat": "{{task_name}} {{job_name}}"
    }
   ]
  },
  {
   "title": "NumBytesIn/sec",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInPerSecond{task_name=~\".*Writer*\", host=~\"$host\"}",
     "legendFormat": "{{task_name}} {{job_name}}"
    }
   ]
  }
 ]
}